### PR TITLE
Additions to migration files \ controllers \ views

### PR DESCRIPTION
**Pull request by savvaq-zz**

### CODE REVIEW

**Review by xinglin2016 — COMMENTED** [review]
Do you think it need to add some very simple code in html.erb file? like <h1>page name</h1>. otherwise those html.erb file will fail to upload?

**Review by HazyHazzy — CHANGES_REQUESTED** [review]
Do you guys have views for the breed and breeders models? I just made empty files for those, so if they exist in your branch you shouldn't have to worry about writing basic code.

**Comment by HazyHazzy** [comment]
Sorry that was not supposed to be a change request lol. I'm a github noob.

**Comment by savvaq-zz** [comment]
I'm the same :D i added some h1s tho to the files

**Comment by savvaq-zz** [comment]
feel free to merge if all good

**Comment by HazyHazzy** [comment]
Ya cool, basic h1s are no problem and good to be safe

**Comment by savvaq-zz** [comment]
I don't know how to mark your requested change as resolved though 🤔

**Comment by HazyHazzy** [comment]
@xinglin2016 can you merge it? I haven't had a chance to actually review the code lol

**Comment by xinglin2016** [comment]
Yes, sure, I will merge it

**Pull request merged**
