### PR TITLE
add user name in database

### PR DESCRIPTION
**Pull request by xinglin2016**
- Add first_name and last_name in user database
- Modify seed file for user part

### CODE REVIEW

**Review by savvaq-zz — COMMENTED** [review]
Are these changes to devise?

**Comment by xinglin2016** [comment]
> Are these changes to devise?

Actually I am not sure, I just generate migration to user model

**Comment by HazyHazzy** [comment]
This is not essential for tonight right? Might be best to just hold off on it to be safe.

**Comment by savvaq-zz** [comment]
I think it looks good tho - should we merge now?

**Pull request merged**
